<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AS-QC-L03" ignored="0" name="Test" tests="2" failures="1" timestamp="10 Mar 2018 09:28:05 GMT" time="0.08" errors="0">
  <testcase name="to_fail" time="0.02" classname="mt.trial_mv">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at mt.trial_mv.to_fail(trial_mv.java:15)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- to_fail -->
  <testcase name="to_pass" time="0.001" classname="mt.trial_mv"/>
</testsuite> <!-- Test -->
